# courses.py
import re

COURSE_CATALOG = {
    # -------------------------------------------------------------
    # 1st Year Core (All Branches)
    # -------------------------------------------------------------
    "MA1101": "Calculus and Linear Algebra",
    "CS1101": "Foundations of Programming",
    "PH1101": "Physics",
    "PH1201": "Physics",
    "CE1101": "Engineering Graphics",
    "CE1201": "Engineering Graphics",
    "EE1101": "Electrical Sciences",
    "EE1201": "Electrical Sciences",
    "HS1101": "English for Professionals",
    "MA1201": "Probability Theory and Ordinary Differential Equations",
    "CS1201": "Data Structure",
    "CH1101": "Chemistry",
    "CH1201": "Chemistry",
    "ME1101": "Mechanical Fabrication",
    "ME1201": "Mechanical Fabrication",
    "ME1102": "Engineering Mechanics",
    "ME1202": "Engineering Mechanics",
    "IK1201": "Indian Knowledge System (IKS)",

    # -------------------------------------------------------------
    # Engineering Physics (EP) & Physics Electives / IDEs (PH)
    # -------------------------------------------------------------
    "EP2101": "Quantum Physics",
    "EP2102": "Optics and Lasers",
    "EP2103": "Classical dynamics: discrete and continuum systems",
    "EP2104": "Thermal physics with engineering applications",
    "EP2201": "Introduction to Nuclear and Particle Physics",
    "EP2202": "Mathematical Methods for Engineers",
    "EP2203": "Electromagnetism",
    "EP2204": "Introductory Statistical Mechanics",
    "EP2205": "Analog Electronics",
    "EP3101": "Computational Techniques",
    "EP3102": "Data Science for Physicists",
    "EP3103": "Digital Electronics and Microprocessors",
    "EP3104": "Solid State Physics",
    "EP3105": "Instrumentation Techniques",
    "EP3201": "Nonlinear Dynamics",
    "EP3202": "Interfacing and data analysis",
    "EP3203": "Atomic and Molecular Physics",
    "EP3204": "Soft Condensed Matter Physics",
    "PH2101": "Energy Storage Fundamentals",
    "PH2201": "Fundamentals of Electromagnetism",
    "PH2202": "Waves and Particles",
    "PH2203": "Fuel Cell Fundamentals",
    "PH3101": "Energy Materials Processing",
    "PH3102": "Mechanics in Physics",
    "PH3201": "Engineering Optics",
    "PH3202": "Cryogenic Engineering",
    "PH3203": "Advanced Quantum Mechanics",
    "PH3204": "Power Sources for Electric Vehicles",
    "PH3205": "Engineering Electromagnetics",
    "PH3206": "Laser Physics",
    "PH3207": "Advanced Mathematical Methods",
    "PH3208": "Electron Microscopy",
    "PH3209": "Quantum Computation",
    "PH3210": "Device Modeling and Design",
    "PH4106": "Science and Technology of Nanomaterials",
    "PH4107": "Optical Quantum Communication",
    "PH4108": "Photovoltaics: Concepts and Applications",
    "PH4109": "Electronic Devices and Circuits",
    "PH4110": "Photovoltaics and Fuel Cell Technology",
    "PH4205": "Quantum Mechanics - II",
    "PH4206": "Thin Film Technology",
    "PH4209": "Solar Energy and Photovoltaics",
    "PH4210": "Modeling Complex Systems",
    "PH4211": "AC Network Analysis",
    "PH4212": "X-ray and Applications",
    "PH4213": "Materials Engineering",
    "PH4214": "Superconducting Qubits: Fundamentals and Operation",
    "PH4215": "Analytical Techniques",
    "PH4216": "Computational Methods for Classical and Quantum Physics",
    "PH4217": "LASER Technology",
    "PH4218": "Atomtronics & Quantum Technology",
    "PH4219": "Nanoscale Devices",
    "PH4220": "Medical Physics and Applications",
    "PH4221": "Emerging Technologies in Photonics",
    "PH4222": "Micro Nano Fabrication",
    "PH4223": "Nanogenerators and Application in Self-powered System",

    # -------------------------------------------------------------
    # Mathematics & Computing (MA)
    # -------------------------------------------------------------
    "MA2101": "Design and Analysis of Algorithms",
    "MA2102": "Probability and Stochastic Processes",
    "MA2103": "Optimization Techniques",
    "MA2104": "Algebra",
    "MA2105": "Discrete Mathematics",
    "MA2201": "Introduction to Machine Learning",
    "MA2202": "Real Analysis and Measure Theory",
    "MA2203": "Numerical Linear Algebra",
    "MA2204": "Computer Architecture and Organization",
    "MA2205": "Database Management Systems",
    "MA2206": "Introduction to Numerical Methods",
    "MA2207": "Complex Analysis",
    "MA3101": "Ordinary and Partial Differential Equations",
    "MA3102": "Complex Analysis",
    "MA3103": "Theory of Computation",
    "MA3104": "Computer Networks",
    "MA3105": "Operating Systems",
    "MA3106": "An Introduction to Computational Commutative Algebra",
    "MA3107": "Partial Differential Equations",
    "MA3201": "Number Theory and Cryptography",
    "MA3202": "Numerical Methods",
    "MA3203": "Mathematical Statistics",
    "MA3204": "Convex Optimization",
    "MA3205": "Functional Analysis",
    "MA3206": "Artificial Intelligence",
    "MA4101": "Advanced Algorithms",
    "MA4102": "Cryptography and Network Security",
    "MA4103": "Rings and Modules",
    "MA4104": "Deep Learning",
    "MA4105": "Fields and Galois Theory",
    "MA4106": "Mathematical Finance",
    "MA4107": "Number Theory and Algebra",
    "MA4108": "Theory of Relativity",
    "MA4201": "Topology",
    "MA4206": "Control Theory",
    "MA4207": "Finite Element Analysis",
    "MA4208": "Introduction to Coding Theory",
    "MA4209": "Portfolio Theory and Risk Management",
    "MA4210": "Differential Geometry",
    "MA4211": "Introduction to Mathematical Biology",
    "MA4212": "Discrete Differential Geometry",
    "MA4213": "Applied Computational Techniques",
    "MA4214": "Deep Learning for Computer Vision",
    "MA4216": "Integral Equations and Calculus of Variations",

    # -------------------------------------------------------------
    # Mechanical Engineering (ME)
    # -------------------------------------------------------------
    "ME2101": "Dynamics",
    "ME2102": "Thermodynamics",
    "ME2103": "Fluid Mechanics",
    "ME2104": "Engineering Materials",
    "ME2201": "Kinematics and Dynamics of Mechanisms",
    "ME2202": "Heat and Mass Transfer",
    "ME2203": "Mechanics of Solids",
    "ME2204": "Mechanical Measurements and Instrumentation",
    "ME2205": "Manufacturing Processes for Metallic Materials",
    "ME3101": "Data Analytics and Machine Learning Tools for Engineers",
    "ME3102": "Design of Machine Elements",
    "ME3103": "Manufacturing Technology- I",
    "ME3104": "Engineering Software Laboratory",
    "ME3105": "Numerical Methods for Engineers",
    "ME3106": "Automotive Technology",
    "ME3201": "Applied Thermodynamics and Turbomachinery",
    "ME3202": "System Dynamics and Control",
    "ME3203": "Manufacturing Technology -II",
    "ME3204": "Industrial Engineering and Operations Research",
    "ME3205": "Technical Writing and Presentations",
    "ME4101": "Tribology and Surface Engineering",
    "ME4102": "Basics of Computational Fluid Dynamics",
    "ME4103": "Industrial Automation",
    "ME4104": "Vehicle Dynamics",
    "ME4105": "Mathematical Modelling of Computer Aided Design",
    "ME4106": "Energy Engineering",
    "ME4201": "Finite Element Method",
    "ME4202": "Refrigeration and Cryogenics",
    "ME4203": "Mechanics, Processing and Failure of Composite Materials",
    "ME4204": "Mechanical Characterization of Materials",
    "ME4205": "Internal Combustion Engines",
    "ME4206": "Micro-manufacturing",
    "ME4207": "Energy Methods and Variational Principles in Applied Mechanics",
    "ME4208": "Failure Analysis of Engineering Materials",
    "ME4209": "Hydraulic Machines",

    # -------------------------------------------------------------
    # Metallurgical & Materials Engineering (MM)
    # -------------------------------------------------------------
    "MM2101": "Introduction to Metallurgical and Materials Engineering",
    "MM2102": "Mineral Processing and Process Metallurgy",
    "MM2103": "Thermodynamics and Phase Equilibria",
    "MM2104": "Transport Phenomena",
    "MM2105": "Fundamentals of Polymer Science and Technology",
    "MM2201": "Iron and Steel Making",
    "MM2202": "Techniques of Materials Characterization - I",
    "MM2203": "Phase Transformation and Diffusion",
    "MM2204": "Mechanical Behaviour of Materials",
    "MM2205": "Welding and Solidification",
    "MM2206": "Structure and Properties of Materials",
    "MM3101": "Thermomechanical Processing of Metallic Materials",
    "MM3102": "Computational Materials Science",
    "MM3103": "Engineering Polymers",
    "MM3104": "Ceramic Science and Technology",
    "MM3105": "Metallography and Heat Treatment Laboratory",
    "MM3106": "Microscopy and X-ray Diffraction",
    "MM3201": "Techniques of Materials Characterization - II",
    "MM3202": "Corrosion and Corrosion Prevention",
    "MM3203": "Functional Materials",
    "MM3204": "Non-ferrous Metals and Alloys",
    "MM3205": "Capstone Laboratory",
    "MM3206": "Metals Processing Laboratory",
    "MM4101": "Environmental Sustainability and Industrial Safety",
    "MM4102": "Glass Science and Technology",
    "MM4103": "Semiconductor Materials and Devices",
    "MM4104": "Thin Films",
    "MM4105": "Heat Treatment of Metals and Alloys",
    "MM4106": "Creep, Fatigue and Fracture",
    "MM4107": "Nanomaterials",
    "MM4201": "Smart Polymers",
    "MM4202": "Energy Materials",
    "MM4203": "Electroceramics",
    "MM4204": "Biomaterials",
    "MM4205": "Crystallographic Texture and Analysis",
    "MM4206": "Furnace and Refractories",
    "MM4207": "Composite Science and Technology",

    # -------------------------------------------------------------
    # Electronics & Communication Engineering (EC)
    # -------------------------------------------------------------
    "EC2101": "Analog Circuits",
    "EC2102": "Signals and Systems",
    "EC2103": "Semiconductor Devices",
    "EC2201": "Digital Electronics",
    "EC2202": "Microprocessor",
    "EC2203": "Computer Organization and Architecture",
    "EC2204": "Internet of Things",
    "EC3101": "Microcontroller and Embedded System",
    "EC3102": "VLSI Design",
    "EC3103": "Analog Communication",
    "EC3104": "Engineering Electromagnetics",
    "EC3105": "Random Signals and Stochastic Processes",
    "EC3106": "Introduction to Communication System",
    "EC3201": "Digital Communication",
    "EC3202": "Digital Signal Processing",
    "EC3203": "Introduction to AI/ML",
    "EC3204": "Low Power MOSFETs Design and Modeling",
    "EC3205": "Introduction to Wireless Communications",
    "EC3206": "RF Systems",
    "EC4101": "Introduction to Quantum Computing",
    "EC4102": "Deep Learning for Video Surveillance Systems",
    "EC4103": "FPGA based System Design",
    "EC4104": "Introduction to Information Theory",
    "EC4105": "Digital Image Processing",
    "EC4106": "Graph Signal Processing",
    "EC4107": "Quantum Computing Fundamentals",
    "EC4201": "Mobile Communications",
    "EC4202": "Opto Electronic Devices",
    "EC4203": "Introduction to Optical Communications",
    "EC4204": "Low Power Circuits",
    "EC4205": "Biomedical Signal Processing",
    "EC4206": "High Power Semiconductor Devices",
    "EC4207": "Biomedical Instrumentation",

    # -------------------------------------------------------------
    # Electrical Engineering (EE)
    # -------------------------------------------------------------
    "EE2101": "Measurements and Instrumentation",
    "EE2102": "Network Analysis and Synthesis",
    "EE2103": "Electrical Machines – I",
    "EE2201": "Control Systems",
    "EE2202": "Electrical Machines-II",
    "EE2203": "Introduction to Electric Vehicle Technology",
    "EE3101": "Power Systems-I",
    "EE3102": "Modern Control Theory",
    "EE3201": "Fundamentals of Electric Drives",
    "EE3202": "Power System II",
    "EE3203": "Power Electronics",
    "EE3204": "Electrical Machine Design",
    "EE4101": "Electrical Traction and Propulsion",
    "EE4102": "Power System Reliability",
    "EE4201": "Power System Protection",
    "EE4202": "Digital Control Systems",
    "EE4203": "Introduction to Energy Storage Techniques",
    "EE4204": "Special Electrical Machines",
    "EE4205": "High Voltage Engineering",
    "EE4206": "Fundamentals of Electrical Vehicle Technology",

    # -------------------------------------------------------------
    # Humanities, Social Sciences & Economics (HS)
    # -------------------------------------------------------------
    "HS2101": "Mathematical Statistics",
    "HS2102": "Fundamentals of Economics",
    "HS2103": "Multivariate Analysis and Basic Econometrics",
    "HS2104": "History of Economic Thought",
    "HS2105": "Probability and Stochastic Processes",
    "HS2106": "Literature: Voices and Culture",
    "HS2107": "Diasporic Literature from South Asia",
    "HS2108": "Soft Skills",
    "HS2109": "Feminist Writing in India",
    "HS2110": "Language Human Mind and Indian Society",
    "HS2111": "Introductory Sociology",
    "HS2112": "Introduction to Demography",
    "HS2113": "Fundamentals of Management",
    "HS2114": "Data Science",
    "HS2115": "Introductory Microeconomics",
    "HS2116": "International Economics",
    "HS2201": "Growth and Development",
    "HS2202": "Microeconomic Theory",
    "HS2203": "Macroeconomic Theory",
    "HS2204": "Econometrics-I",
    "HS2205": "Science, Technology and Society",
    "HS2206": "Healthcare Management",
    "HS2207": "Entrepreneurship",
    "HS2208": "Operations Management",
    "HS2209": "People Management",
    "HS3101": "Econometrics – II",
    "HS3102": "Mathematical Economics",
    "HS3103": "International Trade and Investment",
    "HS3104": "Debate in Indian Economy",
    "HS3105": "Gender and Women's Studies: An Introduction",
    "HS3106": "Fundamentals of Speech Acoustics",
    "HS3107": "Globalization and Social Change",
    "HS3108": "Innovation and Entrepreneurship",
    "HS3109": "Financial Economics",
    "HS3110": "Development Economics",
    "HS3201": "Categorical Data Analysis",
    "HS3202": "Environmental Economics",
    "HS3203": "Critical Economic Reading and Seminar",
    "HS3204": "Indian Financial System",
    "HS3205": "Health Economics",
    "HS4101": "Game Theory",
    "HS4102": "Energy Economics",
    "HS4103": "Labour Economics",
    "HS4104": "Business Law and Economics",
    "HS4105": "Advanced Macroeconomics",
    "HS4106": "Financial Analytics",
    "HS4107": "Behavioural Economics and Finance",
    "HS4108": "Programming/ Coding",
    "HS4109": "Corporate Finance",
    "HS4110": "Programming/ Coding",
    "HS4111": "HR Analytics",
    "HS4112": "Big Data Analytics",
    "HS4114": "IPR: Introduction, Application and Protection",
    "HS4115": "3Ls: Leadership, Literature and Life",
    "HS4116": "Gender in Indian Cinema",
    "HS4117": "Media and Linguistics",
    "HS4118": "Sociology of Development",
    "HS4119": "Industrial Psychology",
    "HS4120": "Business Ethics",
    "HS4121": "Critical and Creative Writing",
    "HS4122": "Forensic Linguistics",
    "HS4123": "Supply Chain Management",
    "HS4201": "Institutional Economics",
    "HS4202": "Public Finance and Policy",
    "HS4203": "Agrarian Economics",
    "HS4204": "Political Economy and Development",
    "HS4205": "Mechanism Design",
    "HS4206": "Financial Markets and Derivatives",
    "HS4207": "Wealth Management",
    "HS4208": "Artificial Intelligence",
    "HS4209": "Statistical Decision Theory",
    "HS4210": "Algorithm with Lab",
    "HS4211": "Machine Learning and DS",

    # -------------------------------------------------------------
    # Chemical & Biochemical Engineering (CB)
    # -------------------------------------------------------------
    "CB2101": "Introduction to Chemical Engineering",
    "CB2102": "Fluid Mechanics",
    "CB2103": "Heat Transfer",
    "CB2104": "Chemical Process Calculations",
    "CB2105": "Chemical Engineering Thermodynamics",
    "CB2201": "Mechanical Operations",
    "CB2202": "Mass Transfer-I",
    "CB2203": "Fundamentals of Biochemical Engineering",
    "CB2204": "Process Dynamics and Control",
    "CB2205": "Chemical Reaction Engineering-I",
    "CB3101": "Mass Transfer-II",
    "CB3102": "Chemical Process Technology",
    "CB3103": "Process Equipment Design",
    "CB3104": "Chemical Reaction Engineering-II",
    "CB3105": "Chemical Process Modeling and Simulation",
    "CB3201": "Process Plant Design and Economics",
    "CB3202": "Transport Phenomena",
    "CB3203": "Numerical Methods in Chemical Engineering",
    "CB3204": "AI/ML for Chemical Engineers",
    "CB3205": "Chemical Plant Safety and Hazards",

    # -------------------------------------------------------------
    # Civil Engineering (CE)
    # -------------------------------------------------------------
    "CE2101": "Geomatics Engineering",
    "CE2102": "Structural Mechanics",
    "CE2103": "Fluid Mechanics",
    "CE2104": "Geology for Engineers",
    "CE2201": "Structural Analysis",
    "CE2202": "Soil Mechanics",
    "CE2203": "Civil Engineering Materials",
    "CE2204": "Water Resources Engineering-I",
    "CE2205": "Numerical Methods in Civil Engineering",
    "CE3101": "Design of Reinforced Concrete Structures",
    "CE3102": "Foundation Engineering",
    "CE3103": "Transportation Engineering - I",
    "CE3104": "Environmental Engineering - I",
    "CE3201": "Design of Steel Structures",
    "CE3202": "Infrastructure Drawing and Estimation",
    "CE3203": "Construction Planning & Management",
    "CE3204": "Environmental Engg-II",
    "CE3205": "Water Resources Engineering - II",
    "CE3206": "Transportation Engineering - II",

    # -------------------------------------------------------------
    # Chemistry / Chemical Technology (CH / CT)
    # -------------------------------------------------------------
    "CH2101": "Organic Chemistry",
    "CH2102": "Inorganic Chemistry",
    "CH2103": "Introduction to Quantum Chemistry",
    "CH2104": "Fluid Mechanics",
    "CH2105": "Chemical Process Calculations",
    "CH2201": "Structure and Function of Biomolecules",
    "CH2202": "Introduction to Organometallics",
    "CH2203": "Chemical Thermodynamics and Equilibrium",
    "CH2204": "Industrial Chemistry",
    "CH2205": "Chemical Technology Laboratory I",
    "CH3101": "Macromolecular Science and Engineering",
    "CH3102": "Design and Applications of Nanomaterials",
    "CH3103": "Chemical Kinetics and Electrochemistry",
    "CH3104": "Techniques for Chemical Analysis",
    "CH3105": "Chemical Technology Laboratory II",
    "CH3201": "Medicinal Chemistry",
    "CH3202": "Environmental Science & Technology",
    "CH3203": "Computational Chemistry",
    "CH3204": "Chemistry for Propellants and Pyrotechnics",
    "CH3205": "Chemical Technology Laboratory III",

    # -------------------------------------------------------------
    # Computer Science & Engineering (CS) & AI/DS
    # -------------------------------------------------------------
    "CS2101": "Algorithm",
    "CS2102": "Digital Logic and Computer Organization",
    "CS2103": "Artificial Intelligence Concepts",
    "CS2104": "Discrete Mathematics",
    "CS2105": "Optimization Techniques",
    "CS2201": "Formal Language and Automata Theory",
    "CS2202": "Database and Warehousing",
    "CS2203": "Artificial Intelligence",
    "CS2204": "IT Workshop",
    "CS2205": "Data Analytics and Visualization",
    "CS2206": "Computer Architecture",
    "CS2207": "Introduction to Data Science",
    "CS3101": "Operating System",
    "CS3102": "Computer Network",
    "CS3103": "Machine Learning",
    "CS3104": "Compiler",
    "CS3105": "Natural Language Processing",
    "CS3106": "Computer Graphics",
    "CS3201": "Cyber Security",
    "CS3202": "Deep Learning",
    "CS3203": "Internet of Things",
    "CS3204": "Computer Vision",
    "CS3205": "Object-Oriented Programming",
    "CS3206": "Agile Computing",
    "CS3207": "Software Engineering",
    "CS3208": "Bayesian Data Analysis",
    "CS3209": "Data Mining",
    "CS3210": "Information Retrieval",
    "CS3299": "Capstone Project",
    "CS4101": "Pattern Recognition",
    "CS4102": "Principles of Programming Languages",
    "CS4103": "Social Networks",
    "CS4104": "Multimedia System",
    "CS4105": "Program Analysis and Verification",
    "CS4106": "Graph Machine Learning",
    "CS4107": "Bioinformatics",
    "CS4108": "Time Series Analysis",
    "CS4109": "Computational Data Analysis",
    "CS4110": "Blockchain Technology",
    "CS4112": "Graph Theory",
    "CS4113": "Data Analysis and Visualization",
    "CS4201": "Multivariate Analysis",
    "CS4202": "Generative AI",
    "CS4203": "Statistical Machine Learning",
    "CS4204": "Text Mining",
    "CS4205": "Cloud Computing",
    "CS4206": "Quantum Computing",
    "CS4207": "Drone Data Processing",
    "CS4208": "Edge Computing",
    "CS4209": "Wireless Networks",
    "CS4210": "Computer Security",
    "CS4211": "Cryptography",
    "CS4212": "Big Data Analytics",
    "CS4213": "Computer Forensics",
    "CS4214": "Combinatorial Optimization",
    "CS4215": "Distributed Computing",
    "CS4216": "Parallel Computing",
}


def lookup_course_name(course_code_str: str) -> str:
    """Extracts base alphanumeric course code and returns full official course title."""
    if not course_code_str:
        return ""
    match = re.search(r"([A-Z]{2,4}\s*\d{3,4}[A-Z]?)", course_code_str, re.IGNORECASE)
    if match:
        clean_code = match.group(1).replace(" ", "").upper()
        return COURSE_CATALOG.get(clean_code, "")
    return COURSE_CATALOG.get(course_code_str.strip().upper(), "")